APP_NAME=Karna-Kavach
APP_ENV=production
APP_KEY=base64:NZtHdpb3M39cXx0YDyexzTvnA5C8TB2NydR1QEL2iC0=
APP_DEBUG=false
APP_URL=https:https://karnakavach.org/

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=wamender_kk
DB_USERNAME=wamender_kk
DB_PASSWORD=wamender_kk

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=public
QUEUE_CONNECTION=database

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_SCHEME=null
MAIL_HOST=mail.karnakavach.org
MAIL_PORT=465
MAIL_USERNAME=noreply@karnakavach.org
MAIL_PASSWORD=TLu]&23jmuie2JwQ
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=noreply@karnakavach.org
MAIL_FROM_NAME="${APP_NAME}"
MAIL_ADMIN_ADDRESS=noreply@karnakavach.org

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"


JWT_SECRET=mGMeb4vvKusr6oaY56VQ0lODMBYfI92QFSWGUfnhdpScTNM8yeh1RVYzpQOYLAFM
